---

- name: Install the package "libssl-dev"
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - libcurl4-openssl-dev
    - pkg-config
    - libssl-dev
    - libsslcommon2-dev

- name: Creates directory
  file: path={{ download_tmp }} state=directory

- name: Unarchive mongodb-1.3.4.tgz
  unarchive: src=mongodb-1.3.4.tgz dest={{ download_tmp }}

- name: Do Phpize mongodb
  command: 'chdir={{ download_tmp }}/mongodb-1.3.4 phpize'

- name: Configure
  command: 'chdir={{ download_tmp }}/mongodb-1.3.4 ./configure'

- name: Make mongodb
  command: 'chdir={{ download_tmp }}/mongodb-1.3.4 make'

- name: Make Install The mongodb
  command: 'chdir={{ download_tmp }}/mongodb-1.3.4 make install'

- name: Gen the ini file
  copy: content="extension=mongodb.so" dest={{ so_ini_path }}/mongodb.ini force=yes

- name: Fetch ini
  fetch: dest=roles/phpext/templates/ src={{ so_ini_path }}/{{ item }} flat=yes
  with_items:
    - mongodb.ini

- name: Fetch so
  fetch: dest=roles/phpext/files/ src={{ so_path }}/{{ item }} flat=yes
  with_items:
    - mongodb.so