---

- name: Creates directory
  file: path={{ download_tmp }} state=directory

- name: Unarchive rabbitmq-c-0.8.0.tar.gz
  unarchive: src=rabbitmq-c-0.8.0.tar.gz dest={{ download_tmp }}

- name: Configure
  command: 'chdir={{ download_tmp }}/rabbitmq-c-0.8.0 ./configure'

- name: Make rabbitmq-c
  command: 'chdir={{ download_tmp }}/rabbitmq-c-0.8.0 make'

- name: Make Install The rabbitmq-c
  command: 'chdir={{ download_tmp }}/rabbitmq-c-0.8.0 make install'

- name: Unarchive amqp-1.9.3.tgz
  unarchive: src=amqp-1.9.3.tgz dest={{ download_tmp }}

- name: Do Phpize Amqp
  command: 'chdir={{ download_tmp }}/amqp-1.9.3 phpize'

- name: Configure
  command: 'chdir={{ download_tmp }}/amqp-1.9.3 ./configure'

- name: Make Amqp
  command: 'chdir={{ download_tmp }}/amqp-1.9.3 make'

- name: Make Install The Amqp
  command: 'chdir={{ download_tmp }}/amqp-1.9.3 make install'

- name: Gen the ini file
  copy: content="extension=amqp.so" dest={{ so_ini_path }}/amqp.ini force=yes

- name: Fetch ini
  fetch: dest=roles/phpext/templates/ src={{ so_ini_path }}/{{ item }} flat=yes
  with_items:
    - amqp.ini

- name: Fetch so
  fetch: dest=roles/phpext/files/ src={{ so_path }}/{{ item }} flat=yes
  with_items:
    - amqp.so