---

- name: Creates directory
  file: path={{ download_tmp }} state=directory

- name: Unarchive php-7.1.0.tar.gz
  unarchive: src=php-7.1.0.tar.gz dest={{ download_tmp }}

- name: Do Phpize Pcntl
  command: 'chdir={{ download_tmp }}/php-7.1.0/ext/pcntl phpize'

- name: Configure
  command: 'chdir={{ download_tmp }}/php-7.1.0/ext/pcntl ./configure'

- name: Make Pcntl
  command: 'chdir={{ download_tmp }}/php-7.1.0/ext/pcntl make'

- name: Make Install The Pcntl
  command: 'chdir={{ download_tmp }}/php-7.1.0/ext/pcntl make install'

- name: Add pcntl.so to php modules
  copy: src=pcntl.ini dest=/etc/php/7.1/mods-available/pcntl.ini force=yes

- name: Create symlink to pcntl.so for cli
  file: src=/etc/php/7.1/mods-available/pcntl.ini dest=/etc/php/7.1/cli/conf.d/pcntl.ini state=link

- name: Create symlink to pcntl.so for fpm
  file: src=/etc/php/7.1/mods-available/pcntl.ini dest=/etc/php/7.1/fpm/conf.d/pcntl.ini state=link

- name: Restart php-fpm
  service:
    name: php7.1-fpm
    state: restarted